x-factorial-env: &factorial_env
  FACTORIAL_KAFKA_BOOTSTRAP: kafka1:9092,kafka2:9092,kafka3:9092
  FACTORIAL_KAFKA_TOPIC_TASKS: factorial.tasks
  FACTORIAL_KAFKA_TOPIC_RESULTS: factorial.results
  FACTORIAL_KAFKA_GROUP_RESULTS: factorial-results-consumer

x-app-env: &app_env
  <<: *factorial_env

x-db-env: &db_env
  POSTGRES_USER: pr-assignment
  POSTGRES_PASSWORD: pr-assignment

x-db: &db_base
  image: postgres:15
  environment: *db_env
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pr-assignment} -d ${POSTGRES_DB:-pr-assignment}"]
    interval: 5s
    timeout: 3s
    retries: 10

x-app: &app_base
  build:
    context: .
  environment: *app_env

services:
  db_test:
    <<: *db_base
    container_name: pr-assignment-db-test
    environment:
      <<: *db_env
      POSTGRES_DB: pr-assignment-test
    ports:
      - "55432:5432"
    volumes:
      - pr_assignment_test_data:/var/lib/postgresql/data
    restart: "no"

  migrate_test:
    image: migrate/migrate:4
    container_name: pr-assignment-migrations-test
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://pr-assignment:pr-assignment@db_test:5432/pr-assignment-test?sslmode=disable",
        "up"
      ]
    volumes:
      - ./database/migrations:/migrations
    depends_on:
      db_test:
        condition: service_healthy
    restart: "no"

  app_test:
    <<: *app_base
    container_name: pr-assignment-service-test
    environment:
      <<: *app_env
      DATABASE_URL: postgres://pr-assignment:pr-assignment@db_test:5432/pr-assignment-test?sslmode=disable
      AUTH_KEY: test-secret
    ports:
      - "18080:8080"
    depends_on:
      migrate_test:
        condition: service_completed_successfully
      kafka-init:
        condition: service_completed_successfully
      kafka1:
        condition: service_started
      kafka2:
        condition: service_started
      kafka3:
        condition: service_started
    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 3s
      timeout: 3s
      retries: 10
    restart: "no"

  tests:
    image: golang:1.23-bullseye
    working_dir: /app
    volumes:
      - .:/app
    container_name: pr-assignment-integration-tests
    depends_on:
      app_test:
        condition: service_healthy
    environment:
      <<: *app_env
      API_BASE_URL: http://app_test:8080
      DATABASE_URL: postgres://pr-assignment:pr-assignment@db_test:5432/pr-assignment-test?sslmode=disable
      AUTH_KEY: test-secret
    command: ["sh", "-c", "go test ./tests/integration/... -v -count=1 | tee /app/test-integration-report.log"]
    restart: "no"
volumes:
  pr_assignment_test_data:
