x-factorial-env: &factorial_env
  FACTORIAL_KAFKA_BOOTSTRAP: ${FACTORIAL_KAFKA_BOOTSTRAP}
  FACTORIAL_KAFKA_TOPIC_TASKS: ${FACTORIAL_KAFKA_TOPIC_TASKS}
  FACTORIAL_KAFKA_TOPIC_RESULTS: ${FACTORIAL_KAFKA_TOPIC_RESULTS}
  FACTORIAL_KAFKA_GROUP_RESULTS: ${FACTORIAL_KAFKA_GROUP_RESULTS}
  FACTORIAL_RESULTS_TTL: ${FACTORIAL_RESULTS_TTL}
  FACTORIAL_RESULTS_TIMEOUT: ${FACTORIAL_RESULTS_TIMEOUT}

x-app-env: &app_env
  <<: *factorial_env

x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}

x-db: &db_base
  image: postgres:15
  environment: *db_env
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    interval: 5s
    timeout: 3s
    retries: 10

x-app: &app_base
  build:
    context: .
  environment: *app_env

services:
  db:
    <<: *db_base
    container_name: pr-assignment-db
    environment:
      <<: *db_env
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pr-assignment_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:4
    container_name: pr-assignment-migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]
    volumes:
      - ./database/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy
    restart: "on-failure"

  app:
    <<: *app_base
    container_name: pr-assignment-service
    environment:
      <<: *app_env
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
      AUTH_KEY: ${AUTH_KEY}
      FACTORIAL_RESULTS_CONSUMER_ENABLED: ${FACTORIAL_RESULTS_CONSUMER_ENABLED}
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
      kafka-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "/healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  k6:
    image: grafana/k6:0.47.0
    profiles: ["tests"]
    working_dir: /tests
    volumes:
      - ./loadtests:/tests
      - ./loadtests/reports:/tests/reports
    entrypoint: ["/bin/sh", "-c", "/tests/run-all.sh"]
    depends_on:
      - app
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pr-assignment_data:

networks:
  default:
    name: prassign_default